version: '3.9'

networks:
  adoorei-network:
    driver: bridge

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./challenge-adoorei/.docker/Dockerfile
    networks:
      - adoorei-network
    volumes:
      - ./challenge-adoorei:/app
    ports:
      - "9090:9090"
    depends_on:
        - database

  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      POSTGRES_DB: adoorei-api
    networks:
      - adoorei-network
    ports:
      - "5432:5432"