name: Simulate CI/CD Deploy

on:
  push:
    branches:
      - 'develop'
      - 'master'
      - 'feature/*'

jobs:
  php-lint-with-pint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.2']
        dependency-stability: [ 'stable' ]

  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Laravel Pint
      id: pint
      uses: aglipanci/laravel-pint@v1
      with:
        preset: 'laravel'

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "🚀 Laravel Pint"
        branch: ${{ github.ref }}
        skip_fetch: true
      run: |
        git config --local user.email "
        git config --local user.name "GitHub Actions"

    - name: Push Changes
      id: push-changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

    - name: Install Dependencies
      id: install-dependencies
      if: steps.vendor-cache.outputs.cache-hit != 'true'
      run: composer install --no-ansi --no-interaction --no-progress --no-suggest --prefer-dist

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate Key
      run: php artisan key:generate

    - name: Storage Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run Migrations
      id: run-migrations
      env:
        SESSION_DRIVER: array
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:"
      run: php artisan migrate --env=local

    - name: Run Tests
      id: run-tests
      env:
        SESSION_DRIVER: array
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:"
      run: ./vendor/bin/pest


      deploy:
        name: Deploy
        runs-on: ubuntu-latest
        manual: true
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' && github.event_name == 'push'
        needs: run-tests

        steps:
          - name: Checkout
            uses: actions/checkout@v4