name: Simulate CI/CD Deploy

on:
  push:
    branches:
      - 'develop'
      - 'feature/*'
      - 'master'

jobs:
  php-lint-with-pint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '8.2' ]
        dependency-stability: [ 'stable' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Laravel Pint
        id: LaravelPint
        uses: aglipanci/laravel-pint-action@0.1.0
        with:
          preset: laravel

      - name: Commit changes
        id: git-auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: PHP Linting (Pint)
          skip_fetch: true

      - name: Push changes
        id: git-push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Install Dependencies
        id: InstallDependencies
        if: steps.vendor-cache.outputs.cache-hit != 'true'
        run: |
          composer config --global -a http-basic.github.com x-access-token ${{ secrets.COMPOSE_TOKEN }}
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Copy .env
        id: CopyEnv
        run: |
          cp .env.example .env
          cp .env .env.testing

      - name: Generate key
        id: GenerateKey
        run: php artisan key:generate

      - name: Directory Permissions
        id: DirectoryPermissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Migrations
        id: Migrations
        # Set environment
        env:
          SESSION_DRIVER: array
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: php artisan migrate --env=local

      - name: Execute test(Unit and Feature tests) PestPHP
        id: PestPHP
        env:
          SESSION_DRIVER: array
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: ./vendor/bin/pest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    needs:
      - php-lint-with-pint
